### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by AndrioJonatas** [peter10110/Android-SteamVR-controller#3]
I downloaded Driver Lead and Orion - Ultraleap for Developers... I installed everything right and it doesn't work... Can you tell me if this is currently working?

**Comment by peter10110** [comment]
Hey! Unfortunately I can't really help you out, I haven't touched this project since the last commit which was 6 years ago. It was mainly intended as an experiment/proof of concept and uploaded it mainly for archival reasons. I'm not keeping up with the development of leap motion/ultraleap as well as with SteamVR but it's more than possible that the version I've built this upon doesn't work anymore.
If you want to dig deeper I'd probably look into the repo linked in the readme as this application is only sending data so if something is broken then it's probably on the driver end. But as I said that's also completely out of date and was already being deprecated when I used it 6 years ago.
Overall I probably wouldn't waste time looking into this. It was a proof of concept but was never practical to use.

**Comment by AndrioJonatas** [comment]
> Ei! Infelizmente eu não posso te ajudar, eu não toquei nesse projeto desde o último commit que foi há 6 anos. Foi concebido principalmente como um experimento/prova de conceito e carregado principalmente por razões de arquivo. Não estou acompanhando o desenvolvimento do movimento de salto/ultraleap, bem como com o SteamVR, mas é mais do que possível que a versão em que construí isso não funcione mais. Se você quiser se aprofundar, eu provavelmente examinaria o repositório vinculado no readme, pois este aplicativo está apenas enviando dados; portanto, se algo estiver quebrado, provavelmente está no lado do driver. Mas, como eu disse, isso também está completamente desatualizado e já estava sendo obsoleto quando o usei há 6 anos. No geral, eu provavelmente não perderia tempo investigando isso.

Thanks anyway for your kindness... It's really that this is really useful today! Success in your life!
